# Generated by Django 5.2.11 on 2026-02-18 05:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('core', '0001_initial'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(max_length=10)),
                ('serie', models.CharField(max_length=10)),
                ('numero', models.PositiveIntegerField()),
                ('fecha_emision', models.DateField()),
                ('hora_emision', models.TimeField(blank=True, null=True)),
                ('cliente_tipo_documento', models.CharField(blank=True, max_length=10)),
                ('cliente_numero_documento', models.CharField(blank=True, max_length=20)),
                ('cliente_razon_social', models.CharField(blank=True, max_length=200)),
                ('cliente_direccion', models.CharField(blank=True, max_length=255)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('igv_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('sent', 'Enviado'), ('accepted', 'Aceptado'), ('rejected', 'Rechazado')], default='draft', max_length=20)),
                ('xml_path', models.CharField(blank=True, max_length=500)),
                ('cdr_path', models.CharField(blank=True, max_length=500)),
                ('pdf_path', models.CharField(blank=True, max_length=500)),
                ('sunat_response_code', models.CharField(blank=True, max_length=10)),
                ('sunat_response_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='core.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='catalog.customer')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='inventory.warehouse')),
            ],
            options={
                'db_table': 'invoices',
                'unique_together': {('company', 'tipo_documento', 'serie', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('line_number', models.PositiveIntegerField()),
                ('descripcion', models.CharField(max_length=500)),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=14)),
                ('valor_unitario', models.DecimalField(decimal_places=4, max_digits=14)),
                ('valor_venta', models.DecimalField(decimal_places=2, max_digits=14)),
                ('codigo_tipo_afectacion', models.CharField(default='10', max_length=10)),
                ('igv_monto', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('importe_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_lines', to='invoicing.invoice')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_lines', to='catalog.product')),
            ],
            options={
                'db_table': 'invoice_lines',
                'unique_together': {('invoice', 'line_number')},
            },
        ),
        migrations.CreateModel(
            name='InvoiceSeries',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(max_length=10)),
                ('serie', models.CharField(max_length=10)),
                ('next_number', models.PositiveIntegerField(default=1)),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_series', to='core.company')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_series', to='inventory.warehouse')),
            ],
            options={
                'verbose_name_plural': 'Invoice series',
                'db_table': 'invoice_series',
                'unique_together': {('company', 'tipo_documento', 'serie')},
            },
        ),
    ]
