# Generated by Django 5.2.11 on 2026-02-18 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceline',
            name='codigo_tipo_afectacion',
            field=models.CharField(default='10', help_text='Catálogo 07 SUNAT: 10=Gravado, 20=Exonerado, 30=Inafecto, 40=Gratuito', max_length=10),
        ),
    ]
