# Generated by Django 5.2.11 on 2026-02-18 23:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('core', '0004_company_codigo_pais_company_codigo_sunat_and_more'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('in', 'Entrada'), ('out', 'Salida'), ('adjust', 'Ajuste'), ('purchase', 'Compra'), ('sale', 'Venta'), ('transfer', 'Traspaso')], max_length=20)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=14)),
                ('quantity_after', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('reference_model', models.CharField(blank=True, max_length=50)),
                ('reference_id', models.UUIDField(blank=True, null=True)),
                ('date', models.DateTimeField()),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='core.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements_created', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='catalog.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='inventory.warehouse')),
            ],
            options={
                'db_table': 'stock_movements',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
