# Generated by Django 5.2.1 on 2026-02-19 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_closing_desglose_destino_validacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['order', 'code'], 'verbose_name': 'Cuenta (plan contable)', 'verbose_name_plural': 'Cuentas (libro de cuentas)'},
        ),
        migrations.AlterModelOptions(
            name='accounttype',
            options={'verbose_name': 'Tipo de cuenta', 'verbose_name_plural': 'Tipos de cuenta'},
        ),
        migrations.AlterModelOptions(
            name='bank',
            options={'verbose_name': 'Banco', 'verbose_name_plural': 'Bancos'},
        ),
        migrations.AlterModelOptions(
            name='cashregister',
            options={'verbose_name': 'Caja', 'verbose_name_plural': 'Cajas'},
        ),
        migrations.AlterModelOptions(
            name='cashregisterclosing',
            options={'verbose_name': 'Cierre de caja', 'verbose_name_plural': 'Cierres de caja'},
        ),
        migrations.AlterModelOptions(
            name='cashregisteropening',
            options={'ordering': ['-opened_at'], 'verbose_name': 'Apertura de caja', 'verbose_name_plural': 'Aperturas de caja'},
        ),
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name': 'Moneda', 'verbose_name_plural': 'Monedas'},
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Gasto', 'verbose_name_plural': 'Gastos'},
        ),
        migrations.AlterModelOptions(
            name='expensetype',
            options={'verbose_name': 'Tipo de gasto', 'verbose_name_plural': 'Tipos de gasto'},
        ),
    ]
