# Generated by Django 5.2.11 on 2026-02-18 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='default_warehouse_id',
        ),
        migrations.AddField(
            model_name='user',
            name='default_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_users', to='inventory.warehouse'),
        ),
    ]
