# Generated by Django 5.2.11 on 2026-02-18 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_user_default_warehouse_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='tipo_negocio',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
