# Generated by Django 5.2.11 on 2026-02-18 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_tipo_negocio'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='codigo_pais',
            field=models.CharField(default='PE', max_length=3),
        ),
        migrations.AddField(
            model_name='company',
            name='codigo_sunat',
            field=models.CharField(default='0000', help_text='Establecimiento anexo para XML', max_length=10),
        ),
        migrations.AddField(
            model_name='company',
            name='departamento',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='distrito',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='igv_porcentaje',
            field=models.DecimalField(decimal_places=2, default=18.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='company',
            name='provincia',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='usuario_sol',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
