# Generated by Django 5.2.1 on 2026-02-19 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_add_default_cash_register'),
        ('core', '0004_company_codigo_pais_company_codigo_sunat_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.AlterModelOptions(
            name='companysubscription',
            options={'verbose_name': 'Suscripción de empresa', 'verbose_name_plural': 'Suscripciones de empresas'},
        ),
        migrations.AlterModelOptions(
            name='digitalcertificate',
            options={'verbose_name': 'Certificado digital', 'verbose_name_plural': 'Certificados digitales'},
        ),
        migrations.AlterModelOptions(
            name='invoiceusagelog',
            options={'verbose_name': 'Registro de uso de facturas', 'verbose_name_plural': 'Registros de uso de facturas'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'Rol', 'verbose_name_plural': 'Roles'},
        ),
        migrations.AlterModelOptions(
            name='subscriptionplan',
            options={'verbose_name': 'Plan de suscripción', 'verbose_name_plural': 'Planes de suscripción'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AddField(
            model_name='user',
            name='default_cash_register',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_users', to='accounting.cashregister'),
        ),
    ]
